runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /dist
  static_dir: dist

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto